### ISSUE TITLE
Overlapping condition bitflags

### ISSUE THREAD

**Issue by henninglive** [evenorog/license#1]
Should these bitflags overlap? [1](https://github.com/evenorog/license/blob/7c26864127f8254847c340b822f838898c4a7007/src/conditions.rs#L12), [2](https://github.com/evenorog/license/blob/7c26864127f8254847c340b822f838898c4a7007/src/conditions.rs#L14) and [3](https://github.com/evenorog/license/blob/7c26864127f8254847c340b822f838898c4a7007/src/permissions.rs#L11), [4](https://github.com/evenorog/license/blob/7c26864127f8254847c340b822f838898c4a7007/src/permissions.rs#L13).

**Comment by evenorog** [comment]
No they should not, thank you! I'll fix it asap.
