### ISSUE TITLE
Wasted space in binaries

### ISSUE THREAD

**Issue by henninglive** [evenorog/license#2]
If you add more licenses to this crate, the space used to store license text in binaries might start to add up. Mayb consider adding a [build script](http://doc.crates.io/build-script.html) that compresses the text, then [lazily](https://github.com/rust-lang-nursery/lazy-static.rs) decompress the text when it is accessed. The problem is partly negated by link time optimizations, which will remove unused code from the final binary.

**Comment by evenorog** [comment]
Hmm, lazy decompressing would be at runtime though. I would think compiling the data right into the binary, even though it uses more space, would be better, but I might be wrong.

**Comment by henninglive** [comment]
Yes, it would be a tradeoff, but you would only decompress on first access, maybe you could [feature gate](http://doc.crates.io/manifest.html#the-features-section) it. It is just a suggestion, it might not be worthy it, just something to consider.

**Comment by evenorog** [comment]
Yeah feature gating might be a good solution! I'll look into it when I got the time.

**Comment by jcgruenhage** [comment]
@henninglive do you mean feature gating the (de)compression, or the licenses themselves?
