### ISSUE TITLE
Cannot define a custom error using `thiserror` crate

### ISSUE THREAD

**Issue by Luni-4** [evenorog/license#4]
I'm trying to define a custom error through `thiserror` crate using this code

```rust
use thiserror::Error;

///Error types
#[derive(Debug, Error)]
pub enum Error {
    /// License not parsed correctly.
    #[error("License not parsed correctly")]
    InvalidLicense(#[from] license::ParseError),
}

/// A specialized `Result` type.
pub type Result<T> = ::std::result::Result<T, Error>;
```

but it seems that `ParseError` cannot be retrieved using `#[from]` attribute

**Comment by evenorog** [comment]
Thanks, will fix this when error is available in core.

https://github.com/rust-lang/rust/issues/103765

**Comment by Luni-4** [comment]
Out of curiosity, why do we need to wait until that issue will be closed? Can we use for now an intermediate solution? I am going to take `minijinja` as direct example since I have used that crate recently :smile: 

[Here](https://github.com/mitsuhiko/minijinja/blob/main/minijinja/src/error.rs) how an error is handled

An I can add `#[from] minijinja::Error` to my custom error.

**Comment by evenorog** [comment]
I have never used `thiserror` so I don't know how it works, but I'm assuming `#[from]` requires the `Error` trait to be implemented for this to work? Or does it require another trait to be implemented?

This library is `no-std` so I currently can't implement `Error` without adding additional feature gating for `std` and `alloc`.

**Comment by Luni-4** [comment]
Ahh, if this library is considering even a `no-std` environment we cannot implement `thiserror` because it's a derive macro for `std::error::Error` trait. There is a [workaround](https://github.com/dtolnay/thiserror/pull/64#issuecomment-612570677) but they advise against using that.

In your opinion, what would a possible hack be to fix my problem? For now, I have introduced custom errors through `map_err`, but it does not seem a good solution eh eh 

As an alternative, I might also try [snafu](https://docs.rs/snafu/latest/snafu/index.html), an error handling library which also considers `no-std` environment

**Comment by evenorog** [comment]
I'm only guessing but if it is the `from` attribute that fails, maybe you can implement the `From` trait manually?

```rust
impl From<ParseError> for Error {
   fn from(e: ParseError) -> Error {
       Error::InvalidLicense(e)
   }
}
```

Or is it the `error` attribute that fails?

**Comment by Luni-4** [comment]
Yep, in that case works, just wanted to use the `#[from]` to simplify the code a bit, but it's okay for me this solution. Thanks a lot!

**Comment by Luni-4** [comment]
The error I get with the `#[from]` attribute is:

```rust
src/error.rs:20:22
    |
20  |     InvalidLicense(#[from] license::ParseError),
    |                      ^^^^ method cannot be called on `&ParseError` due to unsatisfied trait bounds
    |
   ::: /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/license-3.2.0/src/lib.rs:159:1
    |
159 | pub struct ParseError(());
    | ---------------------
    | |
    | doesn't satisfy `ParseError: AsDynError<'_>`
    | doesn't satisfy `ParseError: StdError`
    |
    = note: the following trait bounds were not satisfied:
            `ParseError: StdError`
            which is required by `ParseError: AsDynError<'_>`
            `&ParseError: StdError`
            which is required by `&ParseError: AsDynError<'_>`
```

**Comment by Luni-4** [comment]
> Thanks, will fix this when error is available in core.
> 
> [rust-lang/rust#103765](https://github.com/rust-lang/rust/issues/103765)

Hey! This has been merged the last week. We can now provide a [minijinja](https://github.com/mitsuhiko/minijinja/blob/main/minijinja/src/error.rs)  solution for this crate

**Comment by evenorog** [comment]
Great! I will `impl Error` when it hits stable.
