### ISSUE TITLE
Purpose of “DIGIT … FULL STOP” Unicode in Display output?

### ISSUE THREAD

**Issue by wking** [evenorog/license#5]
5b210380 landed a number of non-ASCII UTF-8 characters, and I'm not clear on the intended meaning.

* U+2488 DIGIT ONE FULL STOP
    * Includes a limitation of liability.
    * May be used for commercial purposes.
    * Source code must be made available when the software is distributed.
* U+2489 DIGIT TWO FULL STOP
    * Changes made to the code must be documented.
    * Does not grant trademark rights.
    * May be distributed.
* U+248a DIGIT THREE FULL STOP
    * Does not provide any warranty.
    * May be modified.
    * The license and copyright notice must be included with the software.
* U+248b DIGIT FOUR FULL STOP
    * Does not provide any rights in the patents of contributors.
    * Provides an express grant of patent rights from contributors.
    * Users who interact with the software via network are given the right to receive a copy of the source code.
* U+248c DIGIT FIVE FULL STOP
    * May be used for private purposes.
    * Modifications must be released under the same license.

This feels a bit like [the attribute grouping on choosealicense.org][1], but your groups are a bit different.  And I don't understand the need to go beyond ASCII here, because “1.” looks about as nice or nicer than “⒈” unless you happen to be using a font that includes support for these uncommon characters.  Can you give a bit more background on the intended semantics?

[1]: https://choosealicense.com/licenses/

**Comment by evenorog** [comment]
Yeah I agree, these should probably just be ASCII.
